"""Initial migration, create users and attendance table

Revision ID: c1cfd4355572
Revises: 
Create Date: 2024-08-20 23:53:26.012798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c1cfd4355572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ErrorLog')
    op.drop_table('BuildVersion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BuildVersion',
    sa.Column('SystemInformationID', mssql.TINYINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Database Version', sa.NVARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('VersionDate', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('ModifiedDate', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('SystemInformationID', name='PK__BuildVer__35E58ECAA19BF817')
    )
    op.create_table('ErrorLog',
    sa.Column('ErrorLogID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('ErrorTime', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('UserName', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('ErrorNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ErrorSeverity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ErrorState', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ErrorProcedure', sa.NVARCHAR(length=126, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ErrorLine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ErrorMessage', sa.NVARCHAR(length=4000, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ErrorLogID', name='PK_ErrorLog_ErrorLogID')
    )
    # ### end Alembic commands ###
