apiVersion: v1
kind: Service
metadata:
  name: attendance-app-service
spec:
  selector:
    app: attendance-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
