name: Sync to Azure Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync to Azure Repos
        uses: andrewd48/git-remote-gc@v1
        with:
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          azure-repo-url: 'https://dev.azure.com/mytekglobe/Agile%20Project/_git/user-attendance-microservice-api'
          branch: 'main'
