name: Sync to Azure Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git for Azure Repos
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add Azure remote repository
          git remote add azure https://dev.azure.com/mytekglobe/Agile%20Project/_git/user-attendance-microservice-api
          
          # Configure Git credentials for Azure
          echo "machine dev.azure.com login $(AZURE_DEVOPS_TOKEN) password x" > ~/.netrc
          
      - name: Sync to Azure Repos
        run: |
          git fetch azure
          git push azure main
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
