name: Sync to Azure Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git for Azure Repos
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add Azure remote repository
          git remote add azure https://dev.azure.com/mytekglobe/Agile%20Project/_git/user-attendance-microservice-api

          # Store credentials for the Azure repository
          echo "https://$(AZURE_REPOS_TOKEN):x@dev.azure.com/mytekglobe/Agile%20Project/_git/user-attendance-microservice-api" > ~/.git-credentials
          
      - name: Sync to Azure Repos
        run: |
          git fetch azure
          git push azure main
        env:
          AZURE_REPOS_TOKEN: ${{ secrets.AZURE_REPOS_TOKEN }}
